# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: target_type_database.proto

import sys

_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode("latin1"))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="target_type_database.proto",
    package="target_features",
    syntax="proto3",
    serialized_pb=_b(
        '\n\x1atarget_type_database.proto\x12\x0ftarget_features"\x88\x01\n\x11ShapeCombinations\x12\x42\n\x07targets\x18\x01 \x03(\x0b\x32\x31.target_features.ShapeCombinations.TargetFeatures\x1a/\n\x0eTargetFeatures\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x66\x65\x61ture\x18\x02 \x03(\x02\x62\x06proto3'
    ),
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


_SHAPECOMBINATIONS_TARGETFEATURES = _descriptor.Descriptor(
    name="TargetFeatures",
    full_name="target_features.ShapeCombinations.TargetFeatures",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="name",
            full_name="target_features.ShapeCombinations.TargetFeatures.name",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None,
        ),
        _descriptor.FieldDescriptor(
            name="feature",
            full_name="target_features.ShapeCombinations.TargetFeatures.feature",
            index=1,
            number=2,
            type=2,
            cpp_type=6,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=137,
    serialized_end=184,
)

_SHAPECOMBINATIONS = _descriptor.Descriptor(
    name="ShapeCombinations",
    full_name="target_features.ShapeCombinations",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="targets",
            full_name="target_features.ShapeCombinations.targets",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None,
        ),
    ],
    extensions=[],
    nested_types=[_SHAPECOMBINATIONS_TARGETFEATURES,],
    enum_types=[],
    options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=48,
    serialized_end=184,
)

_SHAPECOMBINATIONS_TARGETFEATURES.containing_type = _SHAPECOMBINATIONS
_SHAPECOMBINATIONS.fields_by_name[
    "targets"
].message_type = _SHAPECOMBINATIONS_TARGETFEATURES
DESCRIPTOR.message_types_by_name["ShapeCombinations"] = _SHAPECOMBINATIONS

ShapeCombinations = _reflection.GeneratedProtocolMessageType(
    "ShapeCombinations",
    (_message.Message,),
    dict(
        TargetFeatures=_reflection.GeneratedProtocolMessageType(
            "TargetFeatures",
            (_message.Message,),
            dict(
                DESCRIPTOR=_SHAPECOMBINATIONS_TARGETFEATURES,
                __module__="target_type_database_pb2"
                # @@protoc_insertion_point(class_scope:target_features.ShapeCombinations.TargetFeatures)
            ),
        ),
        DESCRIPTOR=_SHAPECOMBINATIONS,
        __module__="target_type_database_pb2"
        # @@protoc_insertion_point(class_scope:target_features.ShapeCombinations)
    ),
)
_sym_db.RegisterMessage(ShapeCombinations)
_sym_db.RegisterMessage(ShapeCombinations.TargetFeatures)


# @@protoc_insertion_point(module_scope)
