model:
  type: "feature_extractor"
  backbone: "efficientnet-b1"
  triplet-margin: 10
  image_width: 100
  image_height: 100
training:
  optimizer: 
    type: "SGD"
    lr: 1e-2
    momentum: 0.9
    weight_decay: 1e-5
  epochs: 30
  gpu: true
  batch_size: 25
  save_best: true
  