model:
  type: "classifier"
  backbone: "rexnet-lite0"
  image_size: 224
training:
  optimizer:
    type: "SGD"
    lr: 5e-3
    momentum: 0.9
    weight_decay: 1e-5
  lr_schedule:
    start_lr: 1.0e-4
    max_lr: 1.0e-1
    end_lr: 1.0e-8
    warmup_fraction: 0.33
  epochs: 40
  gpu: true
  batch_size: 120
  save_best: true
