model:
  type: "detection"
  backbone: "vovnet-19-slim-dw"
  fpn: 
    type: "retinanet"
    num_channels: 128
    use_dw: false
    levels: [3, 4, 5, 6]
  retinanet_head:
    num_levels: 4
    use_dw: false
  image_size: 512
  anchors:
    aspect_ratios: [0.5, 1, 2]  # H / W
    sizes: [16, 32, 64, 128]
    scales: [1.0, 1.25, 1.5]
training:
  optimizer: 
    type: "SGD"
    lr: 5e-3
    momentum: 0.9
    weight_decay: 1e-5
  lr_schedule:
    start_lr: 1.0e-6
    max_lr: 1.0e-1
    end_lr: 1.0e-8
    warmup_fraction: 0.1
  epochs: 50
  train_batch_size: 38
  eval_batch_size: 38
  save_best: True
  eval_start_epoch: 8
  
