model:
  type: "detection"
  backbone: "vovnet-19-slim-dw"
  fpn: 
    type: "retinanet"
    num_channels: 128
    use_dw: false
    levels: [3, 4, 5, 6, 7]
  retinanet_head:
    num_levels: 4
    use_dw: false
  img_size: [512, 512]  # H, W
  anchors:
    aspect_ratios: [0.5, 1, 2]  # H / W
    sizes: [16, 32, 64, 128, 256]
    scales: [1.0, 1.25, 1.5]
training:
  optimizer: 
    type: "SGD"
    lr: 5e-3
    momentum: 0.9
    weight_decay: 1e-5
  epochs: 100
  gpu: True
  train_batch_size: 30
  eval_batch_size: 30
  save_best: True
  
