model:
  type: "classification"
  backbone: "vovnet-19-clf-dw"
  image_size: 224
training:
  optimizer:
    type: "AdamW"
    lr: 5.0e-3
    momentum: 0.9
    weight_decay: 1.0e-5
  lr_schedule:
    start_lr: 1.0e-4
    max_lr: 1.0e-1
    end_lr: 1.0e-8
    warmup_fraction: 0.05
  epochs: 15
  batch_size: 1
  eval_start_epoch: 0
