model:
  type: "detection"
  backbone: "vovnet-19-slim-dw"
  image_size: 512
  num_classes: 10
  fpn:
    type: "retinanet"
    num_channels: 128
    use_dw: false
    levels: [3, 4, 5]
  retinanet_head:
    num_levels: 4
    use_dw: false
  anchors:
    aspect_ratios: [0.5, 1, 2]  # H / W
    sizes: [16, 32, 64]
    scales: [1.0, 1.25, 1.5]
training:
  optimizer:
    type: "SGD"
    lr: 1e-4
    momentum: 0.9
    weight_decay: 1e-5
  lr_schedule:
    start_lr: 1.0e-5
    max_lr: 1.0e-1
    end_lr: 1.0e-7
    warmup_fraction: 0.33
  epochs: 50
  train_batch_size: 30
  eval_batch_size: 30
  eval_start_epoch: 10
