package(default_visibility = ["//visibility:public"])

py_library(
    name = "benchmark_inference",
    srcs = ["benchmark_inference.py"],
    deps = [
        "//core:classifier",
        "//core:detector",
    ]
)
