 
name: Python3 CI

on: ["push", "pull_request"]

jobs:

  tox:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout code 
      uses: actions/checkout@v1

    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: '3.6'

    - name: Install tox 
      run: |
        python -m pip install --upgrade pip
        pip install tox
        
    - name: Unit Tests
      run: tox -e unit

    - name: Style 
      run: tox -e style