
name: Python3 CI

on: ["push", "pull_request"]

jobs:

  python:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04, macos-latest]
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('hawk_eye/setup/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-

    - name: Setup Machine
      run: hawk_eye/setup/setup_env.sh

    - name: Authenticate on GCS
      uses: google-github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    #- name: Cache Bazel Deps
    #  id: cache
    #  uses: actions/cache@v2
    #  with:
    #    path: |
    #      ~/.cache/bazel
    #      ~/runs
    #    key: ${{ runner.os }}-bazel

    - name: Test
      run: |
        bazel test //...

    - name: Style Test
      run: flake8

    - name: Ensure .whl Tests Run
      run: ./setup.py test

    - name: Create hawk_eye .whl package
      run: ./setup.py bdist_wheel
