on:
  # Trigger the workflow on push to master to create version.
  # This will also trigger the release workflow.
  push:
    branches:
      - master

name: Create Tag

jobs:

  create_tag:
    name: Create Release
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch tags
        run: git fetch

      - name: Get current version
        run: |
          echo release_version="$(cat version.txt)" >> $GITHUB_ENV


      - name: See if version exists
        run: |
          if [ $(git tag -l v$release_version) ]; then
            echo Version v$release_version already exists.;
          else
            git tag v$release_version;
            git push origin v$release_version;
          fi
